services:
  - type: web
    name: multimedia-site
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn multimedia_project.wsgi
    envVars:
      - key: DJANGO_SECRET_KEY
        value: h5)ukf3lhxgt(#3#&dogjfl4_h2$!5_qsc3bz-g#be%3*$w50c  # Replace this with your actual secret key
      - key: DJANGO_DEBUG
        value: "True"  # Set it to "True" during development if needed
      - key: DJANGO_ALLOWED_HOSTS
        value: multimedia-site-ngk7.onrender.com
      - key: DATABASE_URL
        value: postgresql://multimedia_user:siGoqkdRQtff3Z1jwwa3Nh5DkLL4QlXT@dpg-d05c28a4d50c73et5iq0-a.oregon-postgres.render.com/multimedia_db_630h  # Replace with your actual database URL
